### ISSUE TITLE
Implement ObservableList.removeIf 

### ISSUE THREAD

**Issue by joha78** [rico-projects/rico-projector#29]
The mentioned method has not been implemented

**Comment by joha78** [comment]
If implemented, method CommonUiHeloer.setProperty() can be overworked:
 ```
 for (String keyAndValue : model.getProperties()) {
         if (keyAndValue.startsWith(property + "=")) {
            model.getProperties().remove(keyAndValue);
            break;
         }
      }
```
 =>
`model.getProperties().removeIf(s -> s.startsWith(property + "="));`

**Comment by hendrikebbers** [comment]
ObservableList extends List extends Collection

The Java Collection class has a default implementation of the removeIf method. So it should work or not?

**Comment by joha78** [comment]
Hm. I remember trying this method and that it made an exception. Need to retry.

**Comment by hendrikebbers** [comment]
yes please. Otherwise we should do it since user expect it to be implemented ;)

**Comment by joha78** [comment]
Retried and everything works fine
